version: '3.9'

name: dojima-network

services:

  scripts:
    build: scripts/
    container_name: dojima-scripts
    volumes:
      - "geth-keystore:/home/user/geth-keystore"
      - "geth-config:/geth-config"
      - "dojima-keystore:/home/user/dojima-keystore"
      - "dojima-config:/dojima-config"
      - "hermes-data:/home/user/hermes-data"

  geth:
    hostname: geth
    image: ethereum/client-go:stable
    ports:
      - "127.0.0.1:9545:9545"
      - "127.0.0.1:9551:9551"
      - "127.0.0.1:9546:9546"
      - "127.0.0.1:30304:30304"
    volumes:
      - "geth-data:/geth-data"
      - "geth-keystore:/geth-keystore"
      - "geth-config:/geth-config"
    command:
      - --keystore=/geth-keystore
      - --http
      - --datadir=/geth-data
      - --http.port=9545
      - --http.addr=0.0.0.0
      - --authrpc.vhosts=*
      - --authrpc.port=9551
      - --authrpc.addr=0.0.0.0
      - --http.vhosts=*
      - --http.api=engine,personal,eth,net,web3
      - --http.corsdomain=*
      - --ws
      - --ws.addr=0.0.0.0
      - --ws.api=personal,eth,net,web3,debug,txpool
      - --allow-insecure-unlock
      - --unlock=0x3f1Eae7D46d88F08fc2F8ed27FCb2AB183EB2d0E
      - --password=/geth-data/passphrase
      - --authrpc.jwtsecret=/geth-config/jwt.hex
      - --nodiscover
      - --syncmode=full
      - --state.scheme=hash
      - --dev
      - --dev.period=1
      - --mine
      - --miner.etherbase=0x3f1Eae7D46d88F08fc2F8ed27FCb2AB183EB2d0E
      - --gcmode=archive

  dojimachain:
    hostname: dojima-chain
    image: dojimanetwork1401/dojimachain:ffa1574d2_3.0.0
    volumes:
      - "dojima-data:/dojima-data"
      - "dojima-keystore:/dojima-keystore"
      - "dojima-config:/dojima-config"
    ports:
      - 8549:8549
      - 8550:8550
      - 30303:30303
      - 8548:8548
    env_file:
      - path: "./config/.hermes.env"
        required: false
    command: |
      --mine
      --datadir=/dojima-data
      --keystore=/dojima-keystore
      --unlock=0x0Fe14f0612fdcbef05dCb8bD33DCBD02DAfA46fA
      --miner.etherbase=0x0Fe14f0612fdcbef05dCb8bD33DCBD02DAfA46fA
      --password=/dojima-data/passphrase
      --allow-insecure-unlock
      --http
      --http.api=personal,db,eth,net,web3,txpool,miner,admin,dojimachain
      --http.addr=0.0.0.0
      --port=30303
      --http.port=8549
      --http.corsdomain="*"
      --http.vhosts=*
      --ws
      --ws.origins="*"
      --ws.port=8546
      --ws.addr=0.0.0.0
      --ws.api=personal,db,eth,net,web3,txpool,miner,admin,dojimachain
      --genesisfile=/dojima-config/dojima_genesis.json
      --syncmode=full
      --gcmode=archive

  hermes:
    hostname: hermesnode
    image: dojimanetwork1401/hermes:8514f6d2_1.0.0
    volumes:
      - "hermes-data:/hermes-data"
      - "hermesnode:/root/.hermesnode"
    env_file:
      - path: "./config/.hermes.env"
        required: false
    ports:
      - 26657:26657
      - 26656:26656
      - 127.0.0.1:1317:1317
      - 6060:6060
      - 9090:9090
    entrypoint: /scripts/genesis.sh
    command:
      - hermesnode
      - start
      - --log_level
      - info
      - --log_format
      - plain
      - --rpc.laddr
      - tcp://0.0.0.0:26657
      - --p2p.laddr
      - tcp://0.0.0.0:26656
      - --consensus.create_empty_blocks
      - "false"

  narada:
    hostname: narada
    image: dojimanetwork1401/hermes:8514f6d2_1.0.0
    ports:
      - 5040:5040
      - 6040:6040
      - 9000:9000
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - "narada:/etc/narada"
      - "hermes-data:/hermes-data"
      - "hermesnode:/root/.hermesnode"
    env_file:
      - path: "./config/.hermes.env"
        required: false
    command: [ "scripts/narada.sh", "narada", "-c", "/etc/narada/config.json", "-p", "-l", "debug" ]

volumes:
  geth-data:
  geth-keystore:
  geth-config:
  dojima-keystore:
  dojima-config:
  dojima-data:
  hermesnode:
  hermes-data:
  narada:
